/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "EarlyOtterFeedback": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "EarlyOtterTelemetry": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EarlyOtterWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "FeedbackViewerPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextServerActionsEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}